services:
  frontend:
    image: ghcr.io/timidtlk/observatorio-pnaes:frontend
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}"]
      interval: 1s
      timeout: 5s
      retries: 10
  backend:
    image: ghcr.io/timidtlk/observatorio-pnaes:backend
    build: ./
    ports:
      - "8080:8080"