spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/observatorio
    username: observatorio
    password: securepassword
    platform: postgresql
  jpa:
    database-platform: org.hibernate.dialect.PosgreSQLInnoDBDialect
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000
  sql:
    init:
      data-locations: classpath:db/data.sql
      mode: always
server:
  port: 8080
  error:
    path: /log
    whitelabel:
      enabled: false
api:
  security:
    token:
      secret: ${JWT_SECRET:my_secure_app}