spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${POSTGRES_DATABASE:observatorio}
    username: ${POSTGRES_USERNAME:observatorio}
    password: ${POSTGRES_PASSWORD:password}
    platform: postgresql
  jpa:
    database-platform: org.hibernate.dialect.PosgreSQLInnoDBDialect
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000
  sql:
    init:
      data-locations: classpath:db/data.sql
      mode: always
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:observatoriopnaes@gmail.com}
    password: ${MAIL_PASSWORD:changeme}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
    from: ${MAIL_FROM:${MAIL_USERNAME:observatoriopnaes@gmail.com}}
server:
  port: 8080
  error:
    path: /log
    whitelabel:
      enabled: false
api:
  security:
    token:
      secret: ${JWT_SECRET:example}
logging:
  level:
    org:
      springframework:
        web: DEBUG